# Generated by Django 5.2.5 on 2025-08-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_listing_seller_inquiry'),
        ('user', '0002_profile_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('apartment', 'Apartment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
