# Generated by Django 5.2.5 on 2025-08-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_listing_category_alter_listing_seller_and_more'),
        ('user', '0002_profile_profile_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='recipient',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='listing/photo1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='listing/photo1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='listing/photo1'),
        ),
    ]
