# Generated by Django 5.2.5 on 2025-08-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_inquiry_status_inquiry_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.listing'),
        ),
    ]
