# Generated by Django 5.2.5 on 2025-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_inquiry_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
