# Generated by Django 5.2.5 on 2025-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
